### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by Orinion**
Changes:
1. Update LocalPlayer's team so it won't get outdated after half.
2. Define the task_t outside of the function -> less parameters
3. Remove unnecessary stuff

### CODE REVIEW

**Comment by iseekwonderful** [comment]
Thank you,and the engineBase will be used in aimbot so I reserve it, and i fix some little bug~

**Comment by Orinion** [comment]
Gj :+1:

**Comment by AdsL1221** [comment]
it contains aimbot, if so, a small explanation, download, open with xcode, launch the exec sudo? Thank you!

**Comment by MyNameIsLebronJames** [comment]
@AdsL1221 you know how to use this?

**Comment by iseekwonderful** [comment]
how can you findout out there has a aimbot?

**Comment by gabsens** [comment]
@iseekwonderful  kids ><

**Pull request merged**
